package no.hiof.geofishing.models

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.Exclude
import com.google.firebase.firestore.GeoPoint
import com.google.firebase.firestore.ServerTimestamp

/**
 * Represents a catch.
 * @property id Unique identifier (should be auto-generated by database).
 * @property created When the catch was created (should be auto-generated by database).
 * @property length The length of the fish caught.
 * @property location Latitude and longitude for where the fish was caught (defaults to now).
 * @property lure What type of lure was used to catch the fish.
 * @property picture Url to a photo of the catch.
 * @property place The general area where the fish was caught (should be filled based on location).
 * @property rod What type of rod was used to catch the fish.
 * @property species An enum that identifies the specie of fish.
 * @property title An appropriate title for the post.
 * @property description An appropriate description for the post.
 * @property user A reference to the user that posted the catch (usually id).
 */
data class Catch(
    @Exclude
    @DocumentId
    val id: String? = null,
    @Exclude
    @ServerTimestamp
    val created: Timestamp? = null,
    val description: String? = null,
    val length: Int? = null,
    val location: GeoPoint? = null,
    val lure: String? = null,
    val picture: String? = null,
    val place: String? = null,
    val rod: String? = null,
    val species: Specie? = null,
    val title: String? = null,
    val user: String? = null,
    val weight: Int? = null
)

/**
 * Represents a specie of fish.
 *
 */
enum class Specie {
    COD,
    SAMON
}
