package no.hiof.geofishing.data.entities

import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.Exclude

/**
 * Represents a checklist (one per user).
 *
 * @property id Unique identifier (should be auto-generated by database).
 * @property subscriber A reference to the profile of the user that subscribes (usually id).
 * @property profile A reference to the profile of the user that is being subbed to (usually id).
 */
data class Subscription(
    @Exclude
    @DocumentId
    val id: String? = null,
    val subscriber: String? = null,
    val profile: String? = null
)
