package no.hiof.geofishing.data.entities

import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.Exclude
import java.util.*

/**
 * Represents a checklist (one per user).
 *
 * @property id Unique identifier (should be auto-generated by database).
 * @property completed Whether the item is crossed of or not.
 * @property description A description of the item.
 * @property reminder A time to remind the user to complete the item.
 * @property profile A reference to the profile of the user that created the item (usually id).
 */
data class Todo(
    @Exclude
    @DocumentId
    val id: String? = null,
    val completed: Boolean = false,
    val description: String? = null,
    val reminder: Date? = null,
    val profile: String? = null
)
